-- Fix script: Create the 6 missing tables
-- Run as: sqlplus learnhub/LearnHub123@localhost/orclpdb @fix_missing_tables.sql
SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

PROMPT *** Creating 6 missing tables... ***

-- 1. COURSES
CREATE TABLE "LEARNHUB"."COURSES" 
   (	"COURSE_ID" NUMBER, 
	"TITLE" VARCHAR2(500) NOT NULL ENABLE, 
	"DESCRIPTION" CLOB, 
	"CATEGORY" VARCHAR2(200), 
	"SUBCATEGORY" VARCHAR2(200), 
	"COURSE_LEVEL" VARCHAR2(50), 
	"DURATION_MINUTES" NUMBER, 
	"RATING" NUMBER(3,2), 
	"NUM_REVIEWS" NUMBER, 
	"YOUTUBE_URL" VARCHAR2(500), 
	"THUMBNAIL_URL" VARCHAR2(500), 
	"INSTRUCTOR" VARCHAR2(200), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("COURSE_ID") ENABLE
   ) TABLESPACE "USERS";

PROMPT Created COURSES table

-- 2. FORUM_REPLIES
CREATE TABLE "LEARNHUB"."FORUM_REPLIES" 
   (	"REPLY_ID" NUMBER, 
	"THREAD_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER, 
	"AUTHOR" VARCHAR2(100) NOT NULL ENABLE, 
	"CONTENT" CLOB NOT NULL ENABLE, 
	"IMAGE_URL" VARCHAR2(500), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("REPLY_ID") ENABLE
   ) TABLESPACE "USERS";

PROMPT Created FORUM_REPLIES table

-- 3. FORUM_THREADS
CREATE TABLE "LEARNHUB"."FORUM_THREADS" 
   (	"THREAD_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"AUTHOR" VARCHAR2(100) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(500) NOT NULL ENABLE, 
	"CONTENT" CLOB NOT NULL ENABLE, 
	"IMAGE_URL" VARCHAR2(500), 
	"UPVOTES" NUMBER DEFAULT 0, 
	"DOWNVOTES" NUMBER DEFAULT 0, 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("THREAD_ID") ENABLE
   ) TABLESPACE "USERS";

PROMPT Created FORUM_THREADS table

-- 4. QUESTIONS
CREATE TABLE "LEARNHUB"."QUESTIONS" 
   (	"QUESTION_ID" NUMBER, 
	"QUIZ_ID" NUMBER, 
	"QUESTION_TEXT" CLOB, 
	"OPTION_A" VARCHAR2(1000), 
	"OPTION_B" VARCHAR2(1000), 
	"OPTION_C" VARCHAR2(1000), 
	"OPTION_D" VARCHAR2(1000), 
	"CORRECT_ANSWER" VARCHAR2(10), 
	"EXPLANATION" CLOB, 
	 PRIMARY KEY ("QUESTION_ID") ENABLE
   ) TABLESPACE "USERS";

PROMPT Created QUESTIONS table

-- 5. QUIZZES
CREATE TABLE "LEARNHUB"."QUIZZES" 
   (	"QUIZ_ID" NUMBER, 
	"COURSE_ID" NUMBER, 
	"TITLE" VARCHAR2(500), 
	"DESCRIPTION" CLOB, 
	"PASSING_SCORE" NUMBER, 
	"TIME_LIMIT_MINUTES" NUMBER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("QUIZ_ID") ENABLE
   ) TABLESPACE "USERS";

PROMPT Created QUIZZES table

-- 6. USER_PROFILES
CREATE TABLE "LEARNHUB"."USER_PROFILES" 
   (	"USER_ID" NUMBER, 
	"USERNAME" VARCHAR2(100), 
	"EMAIL" VARCHAR2(200), 
	"SKILL_LEVEL" VARCHAR2(50), 
	"PREFERRED_CATEGORIES" VARCHAR2(500), 
	"LEARNING_GOALS" CLOB, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"PASSWORD_HASH" VARCHAR2(255), 
	"OTP_CODE" VARCHAR2(6), 
	"OTP_EXPIRES" TIMESTAMP (6), 
	"GITHUB_ID" VARCHAR2(50), 
	"GITHUB_USERNAME" VARCHAR2(100), 
	"AVATAR_URL" VARCHAR2(500), 
	"ROLE" VARCHAR2(20) DEFAULT 'student', 
	 PRIMARY KEY ("USER_ID") ENABLE
   ) TABLESPACE "USERS";

PROMPT Created USER_PROFILES table

PROMPT
PROMPT *** All 6 missing tables created! ***
PROMPT *** Now re-importing data from the full backup... ***
PROMPT

-- Re-run the full backup to insert data into the newly created tables
-- (existing tables will get ORA-00955 "name already used" but WHENEVER SQLERROR CONTINUE handles that)
@learnhub_complete_database.sql

PROMPT
PROMPT *** Verifying final state... ***

COLUMN table_name FORMAT A25
PROMPT === ALL TABLES ===
SELECT table_name FROM user_tables ORDER BY table_name;

PROMPT === VIEWS ===
SELECT view_name FROM user_views ORDER BY view_name;

PROMPT === SEQUENCES ===
SELECT sequence_name FROM user_sequences ORDER BY sequence_name;

EXIT;
